// <auto-generated />
using System;
using JobFitScoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace JobFitScoreAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118123604_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobFitScoreAPI.Models.AuditoriaLog", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_auditoria");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_operacao");

                    b.Property<string>("Detalhe")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("detalhe");

                    b.Property<string>("NomeTabela")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome_tabela");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("operacao");

                    b.Property<int?>("RegistroId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("registro_id");

                    b.Property<string>("UsuarioBanco")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("usuario_banco");

                    b.HasKey("IdAuditoria");

                    b.ToTable("AUDITORIA_LOG", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Candidatura", b =>
                {
                    b.Property<int>("IdCandidatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_candidatura");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCandidatura"));

                    b.Property<DateTime>("DataCandidatura")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_candidatura");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("status");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_id");

                    b.Property<int>("VagaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("vaga_id");

                    b.HasKey("IdCandidatura");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VagaId");

                    b.ToTable("CANDIDATURAS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_curso");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<int?>("CargaHoraria")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("carga_horaria");

                    b.Property<string>("Instituicao")
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("instituicao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("nome");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_id");

                    b.HasKey("IdCurso");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CURSOS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_empresa");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiraRefreshToken")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("expira_refresh_token");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("senha");

                    b.HasKey("IdEmpresa");

                    b.ToTable("EMPRESAS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Habilidade", b =>
                {
                    b.Property<int>("IdHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_habilidade");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabilidade"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdHabilidade");

                    b.ToTable("HABILIDADES", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiraRefreshToken")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("expira_refresh_token");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.UsuarioHabilidade", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("usuario_id");

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("habilidade_id");

                    b.Property<int>("IdUsuarioHabilidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_usuario_habilidade");

                    b.HasKey("UsuarioId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("USUARIO_HABILIDADE", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Vaga", b =>
                {
                    b.Property<int>("IdVaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vaga");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVaga"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("titulo");

                    b.HasKey("IdVaga");

                    b.HasIndex("EmpresaId");

                    b.ToTable("VAGAS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.VagaHabilidade", b =>
                {
                    b.Property<int>("VagaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("vaga_id");

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("habilidade_id");

                    b.Property<int>("IdVagaHabilidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_vaga_habilidade");

                    b.HasKey("VagaId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("VAGA_HABILIDADE", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Candidatura", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFitScoreAPI.Models.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Curso", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.UsuarioHabilidade", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFitScoreAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Vaga", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.VagaHabilidade", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFitScoreAPI.Models.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Empresa", b =>
                {
                    b.Navigation("Vagas");
                });
#pragma warning restore 612, 618
        }
    }
}
