// <auto-generated />
using System;
using JobFitScoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobFitScoreAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121014008_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("SEQ_HABILIDADES", "public")
                .IncrementsBy(10);

            modelBuilder.Entity("JobFitScoreAPI.Models.Candidatura", b =>
                {
                    b.Property<int>("IdCandidatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_candidatura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCandidatura"));

                    b.Property<DateTime>("DataCandidatura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_candidatura");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("VagaId")
                        .HasColumnType("integer")
                        .HasColumnName("vaga_id");

                    b.HasKey("IdCandidatura");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VagaId");

                    b.ToTable("CANDIDATURAS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_curso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCurso"));

                    b.Property<int?>("CargaHoraria")
                        .HasColumnType("integer")
                        .HasColumnName("carga_horaria");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Instituicao")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("instituicao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("IdCurso");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CURSOS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiraRefreshToken")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_refresh_token");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha");

                    b.HasKey("IdEmpresa");

                    b.ToTable("EMPRESAS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Habilidade", b =>
                {
                    b.Property<int>("IdHabilidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_habilidade");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("IdHabilidade"), "SEQ_HABILIDADES", "public");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("NomeHabilidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdHabilidade");

                    b.ToTable("HABILIDADES", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiraRefreshToken")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_refresh_token");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.UsuarioHabilidade", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("habilidade_id");

                    b.Property<int>("IdUsuarioHabilidade")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_habilidade");

                    b.HasKey("UsuarioId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("USUARIO_HABILIDADE", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Vaga", b =>
                {
                    b.Property<int>("IdVaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_vaga");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVaga"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("IdVaga");

                    b.HasIndex("EmpresaId");

                    b.ToTable("VAGAS", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.VagaHabilidade", b =>
                {
                    b.Property<int>("VagaId")
                        .HasColumnType("integer")
                        .HasColumnName("vaga_id");

                    b.Property<int>("HabilidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("habilidade_id");

                    b.Property<int>("IdVagaHabilidade")
                        .HasColumnType("integer")
                        .HasColumnName("id_vaga_habilidade");

                    b.HasKey("VagaId", "HabilidadeId");

                    b.HasIndex("HabilidadeId");

                    b.ToTable("VAGA_HABILIDADE", (string)null);
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Candidatura", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFitScoreAPI.Models.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Curso", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.UsuarioHabilidade", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFitScoreAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Vaga", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.VagaHabilidade", b =>
                {
                    b.HasOne("JobFitScoreAPI.Models.Habilidade", "Habilidade")
                        .WithMany()
                        .HasForeignKey("HabilidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobFitScoreAPI.Models.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidade");

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("JobFitScoreAPI.Models.Empresa", b =>
                {
                    b.Navigation("Vagas");
                });
#pragma warning restore 612, 618
        }
    }
}
