BEGIN

    EXECUTE IMMEDIATE 'INSERT INTO "' || USER || '"."USUARIOS" ("ID_USUARIO", "NOME", "EMAIL", "SENHA", "REFRESH_TOKEN", "EXPIRA_REFRESH_TOKEN") VALUES (1, ''Admin'', ''admin@jobfitscore.com'', ''$2a$12$5SqXdv5vuwXtJllVDEK//uOmjVQBTZI0VqwiQbiQ/bO2Jcu717Kly'', NULL, NULL)';

    EXECUTE IMMEDIATE 'INSERT INTO "' || USER || '"."EMPRESAS" ("ID_EMPRESA", "NOME", "CNPJ", "EMAIL", "SENHA", "REFRESH_TOKEN", "EXPIRA_REFRESH_TOKEN") VALUES (1, ''TechFlow Ltda'', ''12345678000190'', ''contato@techflow.com'', ''$2a$12$5SqXdv5vuwXtJllVDEK//uOmjVQBTZI0VqwiQbiQ/bO2Jcu717Kly'', NULL, NULL)';

    EXECUTE IMMEDIATE 'INSERT INTO "' || USER || '"."VAGAS" ("ID_VAGA", "TITULO", "EMPRESA_ID") VALUES (1, ''Desenvolvedor Backend'', 1)';

    EXECUTE IMMEDIATE 'INSERT INTO "' || USER || '"."HABILIDADES" ("ID_HABILIDADE", "NOME") VALUES (1, ''C#'')';

    EXECUTE IMMEDIATE 'INSERT INTO "' || USER || '"."USUARIO_HABILIDADE" ("ID_USUARIO_HABILIDADE", "USUARIO_ID", "HABILIDADE_ID") VALUES (1, 1, 1)';

    EXECUTE IMMEDIATE 'INSERT INTO "' || USER || '"."CURSOS" ("ID_CURSO", "NOME", "INSTITUICAO", "CARGA_HORARIA", "USUARIO_ID") VALUES (1, ''Introdução a C#'', ''FIAP'', 40, 1)';

    EXECUTE IMMEDIATE 'INSERT INTO "' || USER || '"."CANDIDATURAS" ("ID_CANDIDATURA", "USUARIO_ID", "VAGA_ID", "DATA_CANDIDATURA", "STATUS") VALUES (1, 1, 1, SYSDATE, ''Aprovado'')';

    EXECUTE IMMEDIATE 'INSERT INTO "' || USER || '"."VAGA_HABILIDADE" ("ID_VAGA_HABILIDADE", "VAGA_ID", "HABILIDADE_ID") VALUES (1, 1, 1)';

    EXECUTE IMMEDIATE 'INSERT INTO "' || USER || '"."AUDITORIA_LOG" ("ID_AUDITORIA", "NOME_TABELA", "OPERACAO", "REGISTRO_ID", "DETALHE") VALUES (1, ''USUARIOS'', ''INSERT'', 1, ''Seed inicial de dados para testes'')';

    COMMIT;

END;
/
